import { TransactionItemModel } from '../steps/transactions/transactions.model';

/**
 * Catalog of available integration transactions.
 * Seeded when starting a new wizard (all disabled until the user enables them).
 */
export const DEFAULT_TRANSACTION_CATALOG: readonly TransactionItemModel[] = [
  {
    transactionTypeId: 1,
    transactionName: 'Asset Creation',
    tcode: 'AC|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 27,
    transactionName: 'Asset Edit',
    tcode: 'AE|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 33,
    transactionName: 'Asset Split',
    tcode: 'AS|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 39,
    transactionName: 'Asset Tagging',
    tcode: 'AT|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 45,
    transactionName: 'Asset Audit',
    tcode: 'AA|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 87,
    transactionName: 'Asset Transfer',
    tcode: 'ATR|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 159,
    transactionName: 'Asset Retirement',
    tcode: 'AR|I',
    creationTrigger: 'On Save',
    endpointType: 'Inbound',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 12,
    transactionName: 'Profit Center Master',
    tcode: 'MS|PC',
    creationTrigger: 'On Save',
    endpointType: 'Master',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 13,
    transactionName: 'Asset Class Master',
    tcode: 'MS|ACL',
    creationTrigger: 'On Save',
    endpointType: 'Master',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 14,
    transactionName: 'Location Master',
    tcode: 'MS|LOC',
    creationTrigger: 'On Save',
    endpointType: 'Master',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 16,
    transactionName: 'Sub Location Master',
    tcode: 'MS|SLOC',
    creationTrigger: 'On Save',
    endpointType: 'Master',
    selected: false,
    enabled: false,
  },
  {
    transactionTypeId: 18,
    transactionName: 'Cost Center Master',
    tcode: 'MS|CC',
    creationTrigger: 'On Save',
    endpointType: 'Master',
    selected: false,
    enabled: false,
  },
] as const;
